//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_BlogEntities : DbContext
    {
        public db_BlogEntities()
            : base("name=db_BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_articles> tb_articles { get; set; }
        public virtual DbSet<tb_comments> tb_comments { get; set; }
        public virtual DbSet<tb_friend_links> tb_friend_links { get; set; }
        public virtual DbSet<tb_labels> tb_labels { get; set; }
        public virtual DbSet<tb_set_article_label> tb_set_article_label { get; set; }
        public virtual DbSet<tb_set_article_sort> tb_set_article_sort { get; set; }
        public virtual DbSet<tb_sorts> tb_sorts { get; set; }
        public virtual DbSet<tb_users> tb_users { get; set; }
    }
}
