//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_announcement
    {
        public long announce_id { get; set; }
        public string announce_title { get; set; }
        public string announce_content { get; set; }
        public string announce_publish_time { get; set; }
    }
}
