//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_articles
    {
        public long article_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string article_title { get; set; }
        public string article_content { get; set; }
        public string article_description { get; set; }
        public string article_label_img { get; set; }
        public long article_views { get; set; }
        public long article_comment_count { get; set; }
        public System.DateTime article_date { get; set; }
        public long article_like_count { get; set; }
        public string article_keyword { get; set; }
    
        public virtual tb_users tb_users { get; set; }
    }
}
