//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comments
    {
        public long comment_id { get; set; }
        public long user_id { get; set; }
        public long article_id { get; set; }
        public long comment_like_count { get; set; }
        public System.DateTime comment_date { get; set; }
        public string comment_content { get; set; }
        public long parent_comment_id { get; set; }
    
        public virtual tb_articles tb_articles { get; set; }
        public virtual tb_users tb_users { get; set; }
    }
}
