//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_friend_links
    {
        public long friend_link_id { get; set; }
        public string friend_links { get; set; }
        public string friend_link_name { get; set; }
        public string friend_link_description { get; set; }
        public string friend_link_logo { get; set; }
    }
}
