//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_users()
        {
            this.tb_articles = new HashSet<tb_articles>();
            this.tb_comments = new HashSet<tb_comments>();
        }
    
        public long user_id { get; set; }
        public string user_ip { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string user_email { get; set; }
        public string user_profile_photo { get; set; }
        public string user_level { get; set; }
        public string user_rights { get; set; }
        public System.DateTime user_registration_time { get; set; }
        public Nullable<System.DateTime> user_birthday { get; set; }
        public Nullable<int> user_age { get; set; }
        public long user_telephone_number { get; set; }
        public string user_nickname { get; set; }
        public Nullable<long> user_login_count { get; set; }
        public Nullable<System.DateTime> user_login_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_articles> tb_articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comments> tb_comments { get; set; }
    }
}
